# Generated by Django 3.1.5 on 2021-03-05 07:24

import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoCommittee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positionAssigned', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'CoCommittee',
                'verbose_name_plural': 'CoCommittees',
            },
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('committeeName', models.CharField(max_length=100)),
                ('committeeDescription', models.TextField()),
                ('committeeDept', models.CharField(choices=[('CSE', 'Computer Science'), ('COMPS', 'Computer'), ('IT', 'Information Technology'), ('EXTC', 'Electronics & Telecommunication'), ('MECH', 'Mechanical'), ('BIO', 'Biomedical'), ('ELEX', 'Electronics'), ('CHEM', 'Chemical')], max_length=5)),
                ('committeeChairperson', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Committee',
                'verbose_name_plural': 'Committees',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('sap', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='SAP ID must be valid', regex='^\\+?6?\\d{10,12}$')])),
                ('department', models.CharField(choices=[('CSE', 'Computer Science'), ('COMPS', 'Computer'), ('IT', 'Information Technology'), ('EXTC', 'Electronics & Telecommunication'), ('MECH', 'Mechanical'), ('BIO', 'Biomedical'), ('ELEX', 'Electronics'), ('CHEM', 'Chemical')], max_length=5)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('positionAssigned', models.CharField(max_length=200)),
                ('department', models.CharField(choices=[('CSE', 'Computer Science'), ('COMPS', 'Computer'), ('IT', 'Information Technology'), ('EXTC', 'Electronics & Telecommunication'), ('MECH', 'Mechanical'), ('BIO', 'Biomedical'), ('ELEX', 'Electronics'), ('CHEM', 'Chemical')], max_length=5)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.committee')),
            ],
            options={
                'verbose_name': 'Faculty',
                'verbose_name_plural': 'Faculties',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventDescription', models.TextField()),
                ('eventSummary', models.CharField(max_length=500)),
                ('eventName', models.CharField(max_length=100)),
                ('eventDate', models.DateField()),
                ('eventTime', models.TimeField()),
                ('eventSeatingCapacity', models.IntegerField()),
                ('eventVenue', models.TextField()),
                ('registrationLink', models.URLField()),
                ('is_referral', models.BooleanField(default=False)),
                ('contactName1', models.CharField(default='dummy user', max_length=100)),
                ('contactName2', models.CharField(blank=True, max_length=100, null=True)),
                ('contactNumber1', models.CharField(default='0000000000', max_length=10)),
                ('contactNumber2', models.CharField(blank=True, max_length=10, null=True)),
                ('organisingCommittee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.committee')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='EventLikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.events')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.students')),
            ],
            options={
                'verbose_name': 'EventLikes',
                'verbose_name_plural': 'EventLikes',
            },
        ),
        migrations.CreateModel(
            name='EventImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.events')),
            ],
            options={
                'verbose_name': 'EventImages',
                'verbose_name_plural': 'EventImages',
            },
        ),
        migrations.CreateModel(
            name='CoreCommittee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positionAssigned', models.CharField(max_length=200)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.committee')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.students')),
            ],
            options={
                'verbose_name': 'CoreCommittee',
                'verbose_name_plural': 'CoreCommittees',
            },
        ),
        migrations.CreateModel(
            name='CommitteeToSubscribers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.committee')),
                ('subscribers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.students')),
            ],
            options={
                'verbose_name': 'CommitteeToSubscriber',
                'verbose_name_plural': 'CommitteeToSubscribers',
            },
        ),
        migrations.CreateModel(
            name='CoCommitteeTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField()),
                ('assigned_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.corecommittee')),
                ('coCommittee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cocommittee')),
            ],
            options={
                'verbose_name': 'CoCommitteeTask',
                'verbose_name_plural': 'CoCommitteeTasks',
            },
        ),
        migrations.CreateModel(
            name='CoCommitteeReferals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant', models.CharField(blank=True, max_length=100, null=True)),
                ('coCommittee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cocommittee')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.events')),
            ],
            options={
                'verbose_name': 'CoCommitteeReferal',
                'verbose_name_plural': 'CoCommitteeReferals',
            },
        ),
        migrations.AddField(
            model_name='cocommittee',
            name='committee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.committee'),
        ),
        migrations.AddField(
            model_name='cocommittee',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.students'),
        ),
    ]
