# Generated by Django 3.1.5 on 2021-01-26 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cocommittee",
            options={
                "verbose_name": "CoCommittee",
                "verbose_name_plural": "CoCommittees",
            },
        ),
        migrations.AlterModelOptions(
            name="committee",
            options={
                "verbose_name": "Committee",
                "verbose_name_plural": "Committees",
            },
        ),
        migrations.AlterModelOptions(
            name="committeetosubscribers",
            options={
                "verbose_name": "CommitteeToSubscriber",
                "verbose_name_plural": "CommitteeToSubscribers",
            },
        ),
        migrations.AlterModelOptions(
            name="corecommittee",
            options={
                "verbose_name": "CoreCommittee",
                "verbose_name_plural": "CoreCommittees",
            },
        ),
        migrations.AlterModelOptions(
            name="eventimages",
            options={
                "verbose_name": "EventImages",
                "verbose_name_plural": "EventImages",
            },
        ),
        migrations.AlterModelOptions(
            name="eventlikes",
            options={
                "verbose_name": "EventLikes",
                "verbose_name_plural": "EventLikes",
            },
        ),
        migrations.AlterModelOptions(
            name="events",
            options={"verbose_name": "Event", "verbose_name_plural": "Events"},
        ),
        migrations.AlterModelOptions(
            name="students",
            options={
                "verbose_name": "Student",
                "verbose_name_plural": "Students",
            },
        ),
    ]
