# Generated by Django 3.1.5 on 2021-01-28 12:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_auto_20210126_1238"),
    ]

    operations = [
        migrations.AlterField(
            model_name="committee",
            name="committeeDept",
            field=models.CharField(
                choices=[
                    ("COMPS", "Computer"),
                    ("IT", "Information Technology"),
                    ("EXTC", "Electronics & Telecommunication"),
                    ("MECH", "Mechanical"),
                    ("BIO", "Biomedical"),
                    ("ELEX", "Electronics"),
                    ("CHEM", "Chemical"),
                ],
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="students",
            name="department",
            field=models.CharField(
                choices=[
                    ("COMPS", "Computer"),
                    ("IT", "Information Technology"),
                    ("EXTC", "Electronics & Telecommunication"),
                    ("MECH", "Mechanical"),
                    ("BIO", "Biomedical"),
                    ("ELEX", "Electronics"),
                    ("CHEM", "Chemical"),
                ],
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="students",
            name="sap",
            field=models.CharField(
                default=None,
                max_length=12,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="SAP ID must be valid",
                        regex="^\\+?6?\\d{10,12}$",
                    )
                ],
            ),
        ),
    ]
