# Generated by Django 3.1.5 on 2021-01-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_auto_20210128_1736"),
    ]

    operations = [
        migrations.AlterField(
            model_name="committee",
            name="committeeDept",
            field=models.CharField(max_length=100),
        ),
    ]
