# Generated by Django 3.1.5 on 2021-02-21 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210128_1741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='is_payable',
            new_name='is_referal',
        ),
        migrations.RemoveField(
            model_name='cocommittee',
            name='referralCount',
        ),
        migrations.AddField(
            model_name='events',
            name='contactName1',
            field=models.CharField(default='dummy user', max_length=100),
        ),
        migrations.AddField(
            model_name='events',
            name='contactName2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='contactNumber1',
            field=models.CharField(default='0000000000', max_length=10),
        ),
        migrations.AddField(
            model_name='events',
            name='contactNumber2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='department',
            field=models.CharField(choices=[('CSE', 'Computer Science'), ('COMPS', 'Computer'), ('IT', 'Information Technology'), ('EXTC', 'Electronics & Telecommunication'), ('MECH', 'Mechanical'), ('BIO', 'Biomedical'), ('ELEX', 'Electronics'), ('CHEM', 'Chemical')], max_length=5),
        ),
        migrations.CreateModel(
            name='CoCommitteeTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField()),
                ('coCommittee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cocommittee')),
            ],
            options={
                'verbose_name': 'CoCommitteeTask',
                'verbose_name_plural': 'CoCommitteeTasks',
            },
        ),
        migrations.CreateModel(
            name='CoCommitteeReferals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(blank=True, max_length=100, null=True)),
                ('coCommittee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cocommittee')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.events')),
            ],
            options={
                'verbose_name': 'CoCommitteeReferal',
                'verbose_name_plural': 'CoCommitteeReferals',
            },
        ),
    ]
